/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Presentation;

import javax.swing.JOptionPane;

/**
 *
 * @author Nuno
 */
public class Componentes_Obrigatorias extends javax.swing.JFrame {

    /**
     * Creates new form Componentes_Obrigatorias
     */
    public Componentes_Obrigatorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pinturaB = new javax.swing.JRadioButton();
        jantesB = new javax.swing.JRadioButton();
        pneuB = new javax.swing.JRadioButton();
        motorB = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nextB = new javax.swing.JButton();
        backB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Componentes Obrigatorias");

        pinturaB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinturaB.setText("Pintura");
        pinturaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinturaBActionPerformed(evt);
            }
        });

        jantesB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jantesB.setText("Jantes");
        jantesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jantesBActionPerformed(evt);
            }
        });

        pneuB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pneuB.setText("Pneu");
        pneuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pneuBActionPerformed(evt);
            }
        });

        motorB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        motorB.setText("Motor");
        motorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorBActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/jante.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/pneu.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/motor.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/tinta.png"))); // NOI18N

        nextB.setText("Next");
        nextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBActionPerformed(evt);
            }
        });

        backB.setText("Back");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(backB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextB)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinturaB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jantesB)
                    .addComponent(pneuB)
                    .addComponent(motorB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinturaB)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jantesB)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pneuB)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorB)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextB)
                    .addComponent(backB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // TODO add your handling code here:
        Pacotes pc = new Pacotes();
        pc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void nextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBActionPerformed
        // TODO add your handling code here:
        if(pinturaB.isSelected() && jantesB.isSelected() && motorB.isSelected() && pneuB.isSelected()){
            Detalhe_Exterior de = new Detalhe_Exterior();
            de.setVisible(true);  
        }else{
            JOptionPane.showMessageDialog(null, "Por Favor Selecione todas as Obrigatorias!");
        }
    }//GEN-LAST:event_nextBActionPerformed

    private void pinturaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinturaBActionPerformed
        // TODO add your handling code here:
        if(pinturaB.isSelected()){
            Pintura cor = new Pintura();
            cor.setVisible(true);
        }
    }//GEN-LAST:event_pinturaBActionPerformed

    private void jantesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jantesBActionPerformed
        // TODO add your handling code here:
        if(jantesB.isSelected()){
            Jantes jt = new Jantes();
            jt.setVisible(true);
        }
    }//GEN-LAST:event_jantesBActionPerformed

    private void pneuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pneuBActionPerformed
        // TODO add your handling code here:
        if(pneuB.isSelected()){
            Pneus pn = new Pneus();
            pn.setVisible(true);
        }        
    }//GEN-LAST:event_pneuBActionPerformed

    private void motorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorBActionPerformed
        // TODO add your handling code here:
        if(motorB.isSelected()){
            Motor mt = new Motor();
            mt.setVisible(true);
        }        
    }//GEN-LAST:event_motorBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jantesB;
    private javax.swing.JRadioButton motorB;
    private javax.swing.JButton nextB;
    private javax.swing.JRadioButton pinturaB;
    private javax.swing.JRadioButton pneuB;
    // End of variables declaration//GEN-END:variables
}
