/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Presentation;

import Main.Business.Ford;
import Main.Data.ComponenteObrigatoriaDAO;
import Main.Data.ComponenteOpcionalDAO;
import Main.Data.DetExteriorDAO;
import Main.Data.DetInteriorDAO;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nuno
 */
public class Definir_Preco_Peca extends javax.swing.JFrame {
    private ComponenteObrigatoriaDAO coDAO;
    private ComponenteOpcionalDAO copDAO;
    private DetExteriorDAO dextDAO;
    private DetInteriorDAO dintDAO;
    private Ford ford;
    /**
     * Creates new form Deinir_Preco_Peca
     */
    public Definir_Preco_Peca(ComponenteObrigatoriaDAO coDAO, ComponenteOpcionalDAO copDAO,
            DetExteriorDAO dextDAO, DetInteriorDAO dintDAO, Ford ford) {
        this.ford=ford;
        this.coDAO=coDAO;
        this.copDAO=copDAO;
        this.dextDAO=dextDAO;
        this.dintDAO=dintDAO;
        initComponents();
        printPecas(coDAO, copDAO, dextDAO, dintDAO);
    }

    /**
     * Vai dar um print do nome de todas as pecas
     * @param coDAO
     * @param copDAO
     * @param dextDAO
     * @param dintDAO 
     */
    public void printPecas(ComponenteObrigatoriaDAO coDAO, ComponenteOpcionalDAO copDAO,
            DetExteriorDAO dextDAO, DetInteriorDAO dintDAO){
        
        HashMap<String,Integer> pecas = ford.listaPecas(coDAO, copDAO, dextDAO, dintDAO);
        
        DefaultListModel jLista = new DefaultListModel();
        
        for(String key : pecas.keySet()){
            jLista.addElement(key);       
        }
        listaPecas.setModel(jLista);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backB = new javax.swing.JToggleButton();
        gravarB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPecas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        precoAtualPeca = new javax.swing.JTextField();
        novoPrecoPeca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Definir Preço Peça");

        backB.setText("Back");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        gravarB.setText("Gravar");
        gravarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarBActionPerformed(evt);
            }
        });

        listaPecas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPecasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPecas);

        jLabel1.setText("Preço atual:");

        jLabel2.setText("Novo Preço:");

        precoAtualPeca.setEditable(false);
        precoAtualPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoAtualPecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gravarB)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(precoAtualPeca, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(novoPrecoPeca))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(precoAtualPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(novoPrecoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backB)
                    .addComponent(gravarB))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBActionPerformed
    /**
     * Vai dar um update na tabela respetiva da base dados aonde se encontra a peca selecionada
     * @param coDAO
     * @param copDAO
     * @param dextDAO
     * @param dintDAO 
     */
    public void gravaUpdate(ComponenteObrigatoriaDAO coDAO, ComponenteOpcionalDAO copDAO,
            DetExteriorDAO dextDAO, DetInteriorDAO dintDAO){
        try{
            int novoValor = Integer.parseInt(novoPrecoPeca.getText());
            
            if(coDAO.containsKey(listaPecas.getSelectedValue().toString())){
                ford.updatePrecoCOB(listaPecas.getSelectedValue().toString(), coDAO, novoValor);
            }
                else if(copDAO.containsKey(listaPecas.getSelectedValue().toString())){
                    ford.updatePrecoCOP(listaPecas.getSelectedValue().toString(), copDAO, novoValor);
                }
                    else if(dextDAO.containsKey(listaPecas.getSelectedValue().toString())){
                        ford.updatePrecoDEXT(listaPecas.getSelectedValue().toString(), dextDAO, novoValor);
                    }
                    else if(dintDAO.containsKey(listaPecas.getSelectedValue().toString())){
                        ford.updatePrecoDINT(listaPecas.getSelectedValue().toString(), dintDAO, novoValor);
                    } 
            else{
                 JOptionPane.showMessageDialog(null, "Peca nao existe!", "ERRO",JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(null, "Gravado com Sucesso");
        
        }catch(Exception e){
            e.getStackTrace();
        }       
    }
    
    private void gravarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarBActionPerformed
        // TODO add your handling code here:
        gravaUpdate(coDAO, copDAO, dextDAO, dintDAO);
        this.dispose();
    }//GEN-LAST:event_gravarBActionPerformed
    /**
     * Vai dar retornar o preco de uma peca e dar print dele num textfield
     * @param coDAO
     * @param copDAO
     * @param dextDAO
     * @param dintDAO 
     */
    public void printPreco(ComponenteObrigatoriaDAO coDAO, ComponenteOpcionalDAO copDAO,
            DetExteriorDAO dextDAO, DetInteriorDAO dintDAO){
        
        HashMap<String,Integer> pecas = ford.listaPecas(coDAO, copDAO, dextDAO, dintDAO);
        
        precoAtualPeca.setText(pecas.get(listaPecas.getSelectedValue()).toString());
    }
    
    private void listaPecasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPecasValueChanged
        // TODO add your handling code here:
        if(evt.getValueIsAdjusting()){ //garante que nao ha multipla seleccao
           printPreco(coDAO, copDAO, dextDAO, dintDAO);
        }
    }//GEN-LAST:event_listaPecasValueChanged

    private void precoAtualPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoAtualPecaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_precoAtualPecaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton backB;
    private javax.swing.JButton gravarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPecas;
    private javax.swing.JTextField novoPrecoPeca;
    private javax.swing.JTextField precoAtualPeca;
    // End of variables declaration//GEN-END:variables
}
