/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Presentation;

import Main.Business.Ford;
import Main.Data.ComponenteObrigatoriaDAO;
import Main.Data.ComponenteOpcionalDAO;
import Main.Data.DetExteriorDAO;
import Main.Data.DetInteriorDAO;

/**
 *
 * @author Nuno
 */
public class Menu_Fabricante extends javax.swing.JFrame {
     private Ford ford;
     private ComponenteObrigatoriaDAO coDAO;
     private ComponenteOpcionalDAO copDAO;
     private DetExteriorDAO dextDAO;
     private DetInteriorDAO dintDAO;
    /**
     * Creates new form MenuFabricante
     */
    public Menu_Fabricante(Ford ford, ComponenteObrigatoriaDAO coDAO, ComponenteOpcionalDAO copDAO,
            DetExteriorDAO dextDAO, DetInteriorDAO dintDAO) {
        this.ford=ford;
        this.coDAO=coDAO;
        this.copDAO=copDAO;
        this.dextDAO=dextDAO;
        this.dintDAO=dintDAO;    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultaPedidos = new javax.swing.JButton();
        verficaStock = new javax.swing.JButton();
        altStock2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Fabricante");

        consultaPedidos.setText("Consultar Pedidos");
        consultaPedidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPedidosActionPerformed(evt);
            }
        });

        verficaStock.setText("Verifica Stock");
        verficaStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verficaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verficaStockActionPerformed(evt);
            }
        });

        altStock2.setText("Alterar Stock");
        altStock2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        altStock2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altStock2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(altStock2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(consultaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(verficaStock, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altStock2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verficaStock, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altStock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altStock2ActionPerformed
        // TODO add your handling code here:
        Alterar_Stock aS = new Alterar_Stock();
        aS.setVisible(true);
    }//GEN-LAST:event_altStock2ActionPerformed

    private void consultaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPedidosActionPerformed
        // TODO add your handling code here:
        Consulta_Pedido cp = new Consulta_Pedido();
        cp.setVisible(true);
                
    }//GEN-LAST:event_consultaPedidosActionPerformed

    private void verficaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verficaStockActionPerformed
        // TODO add your handling code here:
        Verifica_Stock vs = new Verifica_Stock(ford, coDAO, copDAO, dextDAO, dintDAO);
        vs.setVisible(true);
    }//GEN-LAST:event_verficaStockActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altStock2;
    private javax.swing.JButton consultaPedidos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton verficaStock;
    // End of variables declaration//GEN-END:variables
}
