/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.Presentation;

import Main.Data.ConfiguracaoDAO;
import Main.Data.VeiculoDAO;

/**
 *
 * @author Nuno
 */
public class Veiculos extends javax.swing.JFrame {
    private VeiculoDAO veiculos;
    private ConfiguracaoDAO confDAO;
    /**
     * Creates new form Veiculos_
     */
    public Veiculos(VeiculoDAO veiculos, ConfiguracaoDAO confDAO) {
        this.confDAO=confDAO;
        this.veiculos=veiculos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        testeB = new javax.swing.JButton();
        ecosportB = new javax.swing.JButton();
        edgeB = new javax.swing.JButton();
        fiestaB = new javax.swing.JButton();
        galaxyB = new javax.swing.JButton();
        kaB = new javax.swing.JButton();
        kugaB = new javax.swing.JButton();
        focusB = new javax.swing.JButton();
        mondeoB = new javax.swing.JButton();
        mustangB = new javax.swing.JButton();
        tourneoB = new javax.swing.JButton();
        tourneoCB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("Veiculos"); // NOI18N

        testeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/teste.png"))); // NOI18N
        testeB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        testeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testeBActionPerformed(evt);
            }
        });

        ecosportB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/ecosport.png"))); // NOI18N
        ecosportB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ecosportB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecosportBActionPerformed(evt);
            }
        });

        edgeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/edge.png"))); // NOI18N
        edgeB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edgeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgeBActionPerformed(evt);
            }
        });

        fiestaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/fiesta.png"))); // NOI18N
        fiestaB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fiestaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiestaBActionPerformed(evt);
            }
        });

        galaxyB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/galaxy.png"))); // NOI18N
        galaxyB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        galaxyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galaxyBActionPerformed(evt);
            }
        });

        kaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/ka+.png"))); // NOI18N
        kaB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaBActionPerformed(evt);
            }
        });

        kugaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/kuga.png"))); // NOI18N
        kugaB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kugaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kugaBActionPerformed(evt);
            }
        });

        focusB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/focus.png"))); // NOI18N
        focusB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        focusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                focusBActionPerformed(evt);
            }
        });

        mondeoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/mondeo.png"))); // NOI18N
        mondeoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mondeoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondeoBActionPerformed(evt);
            }
        });

        mustangB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/mustang.png"))); // NOI18N
        mustangB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mustangB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mustangBActionPerformed(evt);
            }
        });

        tourneoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/tourneo.png"))); // NOI18N
        tourneoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tourneoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourneoBActionPerformed(evt);
            }
        });

        tourneoCB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Presentation/images/tourneoC.png"))); // NOI18N
        tourneoCB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tourneoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourneoCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mondeoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(galaxyB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(mustangB, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kaB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecosportB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edgeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kugaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tourneoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fiestaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(focusB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tourneoCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testeB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ecosportB)
                    .addComponent(edgeB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiestaB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(focusB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(galaxyB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kugaB, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(kaB, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mondeoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mustangB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tourneoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tourneoCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void focusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_focusBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford FOCUS").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_focusBActionPerformed

    private void testeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testeBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford C-Max").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_testeBActionPerformed

    private void ecosportBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecosportBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford ECOSPORT").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_ecosportBActionPerformed

    private void edgeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgeBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford EDGE").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_edgeBActionPerformed

    private void fiestaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiestaBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford FIESTA").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_fiestaBActionPerformed

    private void galaxyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galaxyBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford GALAXY").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_galaxyBActionPerformed

    private void kaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford KA+").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_kaBActionPerformed

    private void kugaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kugaBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford KUGA").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_kugaBActionPerformed

    private void mondeoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondeoBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford MONDEO").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_mondeoBActionPerformed

    private void mustangBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mustangBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford MUSTANG").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_mustangBActionPerformed

    private void tourneoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourneoBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford TOURNEO COURIER").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_tourneoBActionPerformed

    private void tourneoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourneoCBActionPerformed
        // TODO add your handling code here:
        try{
            int idV = veiculos.get("Ford TOURNEO").getid_V();
            
            confDAO.atribuiConf(idV);
            
            Pacotes pct = new Pacotes(confDAO);
            pct.setVisible(true);
            this.dispose();
        }catch(Exception e){
            e.getStackTrace();
        }
    }//GEN-LAST:event_tourneoCBActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ecosportB;
    private javax.swing.JButton edgeB;
    private javax.swing.JButton fiestaB;
    private javax.swing.JButton focusB;
    private javax.swing.JButton galaxyB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kaB;
    private javax.swing.JButton kugaB;
    private javax.swing.JButton mondeoB;
    private javax.swing.JButton mustangB;
    private javax.swing.JButton testeB;
    private javax.swing.JButton tourneoB;
    private javax.swing.JButton tourneoCB;
    // End of variables declaration//GEN-END:variables
}
