/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface.dss;

/**
 *
 * @author Nuno
 */
public class Pintura extends javax.swing.JPanel {

    /**
     * Creates new form Pintura
     */
    public Pintura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chocolateB = new javax.swing.JButton();
        darkBlueB = new javax.swing.JButton();
        darkOliveGreen = new javax.swing.JButton();
        darkOrangeB = new javax.swing.JButton();
        goldenRodB = new javax.swing.JButton();
        mediumOrchidB = new javax.swing.JButton();
        mediumVioletRedB = new javax.swing.JButton();
        mostardB = new javax.swing.JButton();
        royalBlueB = new javax.swing.JButton();
        paleTurquoiseB = new javax.swing.JButton();
        purpleB = new javax.swing.JButton();
        redB = new javax.swing.JButton();
        blackB = new javax.swing.JButton();
        seaGreenB = new javax.swing.JButton();
        yellowGreenB = new javax.swing.JButton();
        coralB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        grayB = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        darkGrayB = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lightGrayB = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        whiteB = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        backB = new javax.swing.JButton();

        chocolateB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/Chocolate.png"))); // NOI18N
        chocolateB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chocolateB.setMaximumSize(new java.awt.Dimension(70, 70));
        chocolateB.setMinimumSize(new java.awt.Dimension(70, 70));
        chocolateB.setPreferredSize(new java.awt.Dimension(70, 70));

        darkBlueB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/DarkBlue.png"))); // NOI18N
        darkBlueB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        darkBlueB.setMaximumSize(new java.awt.Dimension(70, 70));
        darkBlueB.setMinimumSize(new java.awt.Dimension(70, 70));
        darkBlueB.setPreferredSize(new java.awt.Dimension(70, 70));
        darkBlueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkBlueBActionPerformed(evt);
            }
        });

        darkOliveGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/DarkOliveGreen.png"))); // NOI18N
        darkOliveGreen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        darkOliveGreen.setMaximumSize(new java.awt.Dimension(70, 70));
        darkOliveGreen.setMinimumSize(new java.awt.Dimension(70, 70));
        darkOliveGreen.setPreferredSize(new java.awt.Dimension(70, 70));

        darkOrangeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/DarkOrange.png"))); // NOI18N
        darkOrangeB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        darkOrangeB.setMaximumSize(new java.awt.Dimension(70, 70));
        darkOrangeB.setMinimumSize(new java.awt.Dimension(70, 70));
        darkOrangeB.setPreferredSize(new java.awt.Dimension(70, 70));

        goldenRodB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/Goldenrod.png"))); // NOI18N
        goldenRodB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        goldenRodB.setMaximumSize(new java.awt.Dimension(70, 70));
        goldenRodB.setMinimumSize(new java.awt.Dimension(70, 70));
        goldenRodB.setPreferredSize(new java.awt.Dimension(70, 70));

        mediumOrchidB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/MediumOrchid.png"))); // NOI18N
        mediumOrchidB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumOrchidB.setMaximumSize(new java.awt.Dimension(70, 70));
        mediumOrchidB.setMinimumSize(new java.awt.Dimension(70, 70));
        mediumOrchidB.setPreferredSize(new java.awt.Dimension(70, 70));

        mediumVioletRedB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/MediumVioletRed.png"))); // NOI18N
        mediumVioletRedB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumVioletRedB.setMaximumSize(new java.awt.Dimension(70, 70));
        mediumVioletRedB.setMinimumSize(new java.awt.Dimension(70, 70));
        mediumVioletRedB.setPreferredSize(new java.awt.Dimension(70, 70));

        mostardB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/Mostard.png"))); // NOI18N
        mostardB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mostardB.setMaximumSize(new java.awt.Dimension(70, 70));
        mostardB.setMinimumSize(new java.awt.Dimension(70, 70));
        mostardB.setPreferredSize(new java.awt.Dimension(70, 70));

        royalBlueB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/RoyalBlue.png"))); // NOI18N
        royalBlueB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        royalBlueB.setMaximumSize(new java.awt.Dimension(70, 70));
        royalBlueB.setMinimumSize(new java.awt.Dimension(70, 70));
        royalBlueB.setPreferredSize(new java.awt.Dimension(70, 70));

        paleTurquoiseB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/PaleTurquoise.png"))); // NOI18N
        paleTurquoiseB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paleTurquoiseB.setMaximumSize(new java.awt.Dimension(70, 70));
        paleTurquoiseB.setMinimumSize(new java.awt.Dimension(70, 70));
        paleTurquoiseB.setPreferredSize(new java.awt.Dimension(70, 70));

        purpleB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/Purple.png"))); // NOI18N
        purpleB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        purpleB.setMaximumSize(new java.awt.Dimension(70, 70));
        purpleB.setMinimumSize(new java.awt.Dimension(70, 70));
        purpleB.setPreferredSize(new java.awt.Dimension(70, 70));

        redB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/Red.png"))); // NOI18N
        redB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        redB.setMaximumSize(new java.awt.Dimension(70, 70));
        redB.setMinimumSize(new java.awt.Dimension(70, 70));
        redB.setPreferredSize(new java.awt.Dimension(70, 70));

        blackB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/Black.png"))); // NOI18N
        blackB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        blackB.setMaximumSize(new java.awt.Dimension(70, 70));
        blackB.setMinimumSize(new java.awt.Dimension(70, 70));
        blackB.setPreferredSize(new java.awt.Dimension(70, 70));

        seaGreenB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/SeaGreen.png"))); // NOI18N
        seaGreenB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seaGreenB.setMaximumSize(new java.awt.Dimension(70, 70));
        seaGreenB.setMinimumSize(new java.awt.Dimension(70, 70));
        seaGreenB.setPreferredSize(new java.awt.Dimension(70, 70));

        yellowGreenB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/YellowGreen.png"))); // NOI18N
        yellowGreenB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yellowGreenB.setMaximumSize(new java.awt.Dimension(70, 70));
        yellowGreenB.setMinimumSize(new java.awt.Dimension(70, 70));
        yellowGreenB.setPreferredSize(new java.awt.Dimension(70, 70));

        coralB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/laranjaTorrado.png"))); // NOI18N
        coralB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coralB.setMaximumSize(new java.awt.Dimension(70, 70));
        coralB.setMinimumSize(new java.awt.Dimension(70, 70));
        coralB.setPreferredSize(new java.awt.Dimension(70, 70));

        jLabel1.setText("Chocolate");

        jLabel2.setText("Dark Blue");

        jLabel3.setText("Dark Olive Green");

        jLabel4.setText("Dark Orange");

        jLabel5.setText("Golden Rod");

        jLabel6.setText("Medium Orchid");

        jLabel7.setText("Medium Violet Red");

        jLabel8.setText("Mostard");

        jLabel9.setText("Pale Turquoise");

        jLabel10.setText("Purple");

        jLabel11.setText("Red");

        jLabel12.setText("Royal Blue");

        jLabel13.setText("Sea Green");

        jLabel14.setText("Yellow Green");

        jLabel15.setText("Coral");

        jLabel16.setText("Black");

        grayB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/Gray.png"))); // NOI18N
        grayB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grayB.setMaximumSize(new java.awt.Dimension(70, 70));
        grayB.setMinimumSize(new java.awt.Dimension(70, 70));
        grayB.setPreferredSize(new java.awt.Dimension(70, 70));

        jLabel17.setText("Gray");

        darkGrayB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/darkGray.png"))); // NOI18N
        darkGrayB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        darkGrayB.setMaximumSize(new java.awt.Dimension(70, 70));
        darkGrayB.setMinimumSize(new java.awt.Dimension(70, 70));
        darkGrayB.setPreferredSize(new java.awt.Dimension(70, 70));

        jLabel18.setText("Dark Gray");

        lightGrayB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/lightGray.png"))); // NOI18N
        lightGrayB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lightGrayB.setMaximumSize(new java.awt.Dimension(70, 70));
        lightGrayB.setMinimumSize(new java.awt.Dimension(70, 70));
        lightGrayB.setPreferredSize(new java.awt.Dimension(70, 70));

        jLabel19.setText("Light Gray");

        whiteB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/dss/images/white.png"))); // NOI18N
        whiteB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        whiteB.setMaximumSize(new java.awt.Dimension(70, 70));
        whiteB.setMinimumSize(new java.awt.Dimension(70, 70));
        whiteB.setPreferredSize(new java.awt.Dimension(70, 70));

        jLabel20.setText("White");

        backB.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paleTurquoiseB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(131, 131, 131)
                                                        .addComponent(jLabel10))
                                                    .addComponent(jLabel9)
                                                    .addComponent(seaGreenB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13)
                                                    .addComponent(darkGrayB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel18)
                                                        .addGap(81, 81, 81)
                                                        .addComponent(jLabel17)))
                                                .addGap(68, 68, 68))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(167, 167, 167)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(47, 47, 47))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(43, 43, 43)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(goldenRodB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chocolateB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(yellowGreenB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(purpleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel14)
                                                    .addComponent(grayB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(52, 52, 52)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(redB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(coralB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lightGrayB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel19))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(darkBlueB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mediumOrchidB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mediumVioletRedB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(darkOliveGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(darkOrangeB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(mostardB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(royalBlueB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blackB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(whiteB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel20)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel16))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backB)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chocolateB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(darkOliveGreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(darkOrangeB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(darkBlueB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(goldenRodB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mostardB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mediumVioletRedB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(mediumOrchidB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(royalBlueB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(paleTurquoiseB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(redB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purpleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seaGreenB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yellowGreenB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coralB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blackB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(darkGrayB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grayB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightGrayB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(backB)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void darkBlueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkBlueBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_darkBlueBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JButton blackB;
    private javax.swing.JButton chocolateB;
    private javax.swing.JButton coralB;
    private javax.swing.JButton darkBlueB;
    private javax.swing.JButton darkGrayB;
    private javax.swing.JButton darkOliveGreen;
    private javax.swing.JButton darkOrangeB;
    private javax.swing.JButton goldenRodB;
    private javax.swing.JButton grayB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton lightGrayB;
    private javax.swing.JButton mediumOrchidB;
    private javax.swing.JButton mediumVioletRedB;
    private javax.swing.JButton mostardB;
    private javax.swing.JButton paleTurquoiseB;
    private javax.swing.JButton purpleB;
    private javax.swing.JButton redB;
    private javax.swing.JButton royalBlueB;
    private javax.swing.JButton seaGreenB;
    private javax.swing.JButton whiteB;
    private javax.swing.JButton yellowGreenB;
    // End of variables declaration//GEN-END:variables
}
